### ISSUE TITLE
'mini' rootfs size must be decreased to enable image to fit on an 2GB sdcard

### ISSUE THREAD

**Issue by agrez** [fedberry/fedberry-kickstarts#1]
maybe 1664 MB?

**Comment by Gormartsen** [comment]
How about swap partition ?

**Comment by agrez** [comment]
As I was aiming to fit the image on a 2GB sdcard, I was trying to keep this image as small as possible, thus no swap partition. There wouldn't be much of a rootfs left if we included a swap.

**Comment by Gormartsen** [comment]
Got it!

**Comment by agrez** [comment]
This is fixed.
